name: "Pull Request Verifier"
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - main
concurrency:
  group: ${{ github.repository }}-pull-request-verifier-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  verify:
    name: "Verify"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4
      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
          cache: pip
      - name: "Install dependencies"
        run: |
          # Bash script
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          pip install setuptools wheel
          pip install .
          pip install .[build]
          pip install .[test]
      - name: "Run tests"
        run: |
          # Bash script
          python -m pytest
